
language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build --prefix-paths
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master